/* GENERATED by tools/package_arduino.py --sync from bindings/c/include/nobro_audio.h.
 * Do not edit here - edit the canonical header and re-run the sync. */
#ifndef NOBRO_AUDIO_H
#define NOBRO_AUDIO_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define NOBRO_AUDIO_API_VERSION 0x0100u

typedef enum nobro_audio_state {
    NOBRO_AUDIO_DOWN = 0,
    NOBRO_AUDIO_READY = 1,
    NOBRO_AUDIO_SUSPENDED = 2,
    NOBRO_AUDIO_FAULTED = 3
} nobro_audio_state_t;

typedef enum nobro_audio_result {
    NOBRO_AUDIO_OK = 0,
    NOBRO_AUDIO_INVALID_CONFIG = 1,
    NOBRO_AUDIO_NOT_READY = 2,
    NOBRO_AUDIO_FRAME_TOO_LARGE = 3,
    NOBRO_AUDIO_BACKPRESSURED = 4,
    NOBRO_AUDIO_TRANSPORT_ERROR = 5,
    NOBRO_AUDIO_PARTIAL_IO = 6,
    NOBRO_AUDIO_DEADLINE_MISS = 7
} nobro_audio_result_t;

typedef struct nobro_audio_format {
    uint32_t sample_rate_hz;
    uint16_t samples_per_frame;
    uint8_t channels;
    uint8_t bits_per_sample;
} nobro_audio_format_t;

typedef struct nobro_audio_diagnostics {
    uint32_t playback_frames;
    uint32_t capture_frames;
    uint32_t samples_played;
    uint32_t samples_captured;
    uint32_t backpressure_rejections;
    uint32_t oversized_rejections;
    uint32_t partial_transfers;
    uint32_t transport_errors;
    uint32_t deadline_misses;
    uint32_t recoveries;
} nobro_audio_diagnostics_t;

#ifdef __cplusplus
}
#endif

#endif
