"""Host-side helpers for NobroRTOS contracts."""

from .contracts import (
    AiBackendKind,
    AiModelContract,
    AiRouteDecision,
    AiRoutePolicy,
    AiRoutePreference,
    AiRouteTarget,
    AiRuntimeState,
    Capability,
    CONTRACT_SCHEMA_VERSION,
    Criticality,
    MemoryBudget,
    ModuleSpec,
    NobroContractBundle,
    RosAction,
    RosBridgeDescriptor,
    RosParameter,
    RosService,
    RosTopic,
    capability_mask,
    capabilities_from_mask,
    stable_hash32,
)
from .host_contract import (
    BootDiagnostic,
    HostContract,
    ReportStatusClass,
    find_repo_root,
    load_repo_host_contract,
)
from .distribution import (
    DistributionMetadataReport,
    validate_distribution_metadata,
)
from .reports import (
    BootReportSummary,
    FixedReport,
    ReportKind,
    ReportSlot,
    ReportStatus,
    seal_report,
)
from .sim import (
    ImuSample,
    SensorStubError,
    SensorStubMode,
    SensorStubSimulator,
    ServoCommand,
    ServoSimulator,
    ServoSimulatorError,
)

__all__ = [
    "AiBackendKind",
    "AiModelContract",
    "AiRouteDecision",
    "AiRoutePolicy",
    "AiRoutePreference",
    "AiRouteTarget",
    "AiRuntimeState",
    "Capability",
    "CONTRACT_SCHEMA_VERSION",
    "Criticality",
    "MemoryBudget",
    "ModuleSpec",
    "NobroContractBundle",
    "RosAction",
    "RosBridgeDescriptor",
    "RosParameter",
    "RosService",
    "RosTopic",
    "capability_mask",
    "capabilities_from_mask",
    "stable_hash32",
    "find_repo_root",
    "BootDiagnostic",
    "HostContract",
    "load_repo_host_contract",
    "ReportStatusClass",
    "DistributionMetadataReport",
    "validate_distribution_metadata",
    "FixedReport",
    "BootReportSummary",
    "ReportKind",
    "ReportSlot",
    "ReportStatus",
    "seal_report",
    "ImuSample",
    "SensorStubError",
    "SensorStubMode",
    "SensorStubSimulator",
    "ServoCommand",
    "ServoSimulator",
    "ServoSimulatorError",
]
