[workspace]
resolver = "2"
members = ["crates/nobro-core"]

[workspace.package]
version = "1.0.1"
edition = "2021"
rust-version = "1.85"
license = "GPL-3.0-only"
authors = ["dunknowcoding (YouTube NiusRobotLab)"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
