//! GENERATED by tools/dev/train_motion3_nn.py - do not edit by hand.
//! A 3->8->3 int8 MLP motion classifier (idle/walk/shake),
//! trained on synthetic IMU |accel| windows. Integer-only inference.
pub const WINDOW: usize = 32;
pub const HIDDEN: usize = 8;
pub const FEAT: usize = 3;
pub const NUM_CLASSES: usize = 3;
pub const SHIFT1: u32 = 5;
pub const FEAT_MAX: [i32; FEAT] = [4095, 1522, 463];
pub const W1: [[i8; FEAT]; HIDDEN] = [
    [1, 8, -4],
    [1, -8, -4],
    [-21, -3, 2],
    [-8, 12, 9],
    [-5, 4, 15],
    [18, 18, 48],
    [33, 20, 55],
    [67, 127, 63],
];
pub const B1: [i32; HIDDEN] = [-631, 0, 0, -1062, -1533, -1035, -1259, -493];
pub const W2: [[i8; HIDDEN]; NUM_CLASSES] = [
    [3, -8, 0, -17, 31, -1, -14, -127],
    [6, 2, 30, -33, -3, -15, -48, 85],
    [-6, 14, -6, -30, -15, 62, 50, 73],
];
pub const B2: [i32; NUM_CLASSES] = [11033, 339, -11371];
pub const TRAIN_ACC_MILLI: u32 = 974;
