//! GENERATED by tools/dev/train_motion_nn.py - do not edit by hand.
//! A 3->8->2 int8 MLP motion classifier (idle/active), trained on synthetic
//! IMU |accel| windows. Integer-only inference; see NnMotionClassifier.
pub const WINDOW: usize = 32;
pub const HIDDEN: usize = 8;
pub const FEAT: usize = 3;
pub const SHIFT1: u32 = 5;
/// Per-feature normalization maxima (feature -> int8 via f * 127 / FEAT_MAX[i]).
pub const FEAT_MAX: [i32; FEAT] = [2671, 828, 203];
/// Layer 1 weights [HIDDEN][FEAT] and bias [HIDDEN] (int8 / i32).
pub const W1: [[i8; FEAT]; HIDDEN] = [
    [1, -10, 51],
    [-12, 1, -31],
    [40, 7, 17],
    [21, 42, 18],
    [68, 127, 91],
    [-45, -20, 35],
    [-26, 6, -20],
    [-37, -29, -50],
];
pub const B1: [i32; HIDDEN] = [-171, 0, -106, -253, -920, 1390, 0, 8882];
/// Layer 2 weights [2][HIDDEN] and bias [2].
pub const W2: [[i8; HIDDEN]; 2] = [
    [-1, -49, -28, -22, -93, 10, -12, 92],
    [31, 82, 9, 42, 127, -8, 11, -42],
];
pub const B2: [i32; 2] = [5611, -5611];
/// Training accuracy of the exported integer model (x1000).
pub const TRAIN_ACC_MILLI: u32 = 1000;
