[package]
name = "nobro-services"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
filesystem = ["dep:nobro-storage"]
usb-host = []
display = ["dep:nobro-display"]
shell = []

[dependencies]
nobro-storage = { path = "../nobro_storage", optional = true }
nobro-display = { path = "../nobro_display", optional = true }
