#!/usr/bin/env python3
"""Train a tiny quantized 3-class MLP motion classifier (idle / walk / shake) for
NobroRTOS on-device inference (M33).

Same pipeline as train_motion_nn.py but three classes: synthesize |accel| windows for
idle (tiny noise), walk (moderate periodic sway), and shake (large erratic motion);
extract the same 3 integer features (variance, range, mean-abs successive diff); train a
3 -> 8 -> 3 MLP; quantize to int8 integer inference; validate the integer model; and emit
core/adapters/ai/nn-motion-ai/src/nn3_weights.rs. Run: python tools/train_motion3_nn.py
"""
import os
import numpy as np

WINDOW = 32
HIDDEN = 8
FEAT = 3
NUM_CLASSES = 3
SHIFT1 = 5
RNG = np.random.default_rng(11)
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "core", "adapters", "nn-motion-ai", "src", "nn3_weights.rs")


def synth_window(cls):
    base = 1000.0
    t = np.arange(WINDOW)
    if cls == 0:  # idle
        w = base + RNG.normal(0, RNG.uniform(3, 14), WINDOW)
    elif cls == 1:  # walk: moderate periodic sway
        sway = RNG.uniform(40, 90) * np.sin(2 * np.pi * RNG.uniform(0.08, 0.18) * t + RNG.uniform(0, 6))
        noise = RNG.normal(0, RNG.uniform(15, 35), WINDOW)
        w = base + sway + noise
    else:  # shake: large erratic motion
        sway = RNG.uniform(160, 320) * np.sin(2 * np.pi * RNG.uniform(0.2, 0.45) * t + RNG.uniform(0, 6))
        noise = RNG.normal(0, RNG.uniform(90, 170), WINDOW)
        w = base + sway + noise
    return np.clip(w, 0, 4095).astype(np.int64)


def features_int(w):
    n = len(w)
    mean = int(w.sum() // n)
    var = int(((w - mean) ** 2).sum() // n)
    rng = int(w.max() - w.min())
    mad = int(np.abs(np.diff(w)).sum() // (n - 1))
    return np.array([min(var >> 4, 4095), min(rng, 4095), min(mad, 4095)], dtype=np.int64)


def make_dataset(n_each):
    X, y = [], []
    for _ in range(n_each):
        for cls in range(NUM_CLASSES):
            X.append(features_int(synth_window(cls)))
            y.append(cls)
    return np.array(X, dtype=np.float64), np.array(y, dtype=np.int64)


def main():
    Xi, y = make_dataset(500)
    feat_max = np.maximum(Xi.max(axis=0), 1).astype(np.int64)
    Xn = np.clip((Xi * 127 / feat_max), 0, 127)
    X = Xn / 127.0

    W1 = RNG.normal(0, 0.6, (FEAT, HIDDEN)); b1 = np.zeros(HIDDEN)
    W2 = RNG.normal(0, 0.6, (HIDDEN, NUM_CLASSES)); b2 = np.zeros(NUM_CLASSES)
    Y = np.eye(NUM_CLASSES)[y]
    lr = 0.2
    for _ in range(1400):
        z1 = X @ W1 + b1; h = np.maximum(z1, 0)
        z2 = h @ W2 + b2
        ez = np.exp(z2 - z2.max(axis=1, keepdims=True)); p = ez / ez.sum(axis=1, keepdims=True)
        g2 = (p - Y) / len(X)
        dW2 = h.T @ g2; db2 = g2.sum(axis=0)
        gh = (g2 @ W2.T) * (z1 > 0)
        dW1 = X.T @ gh; db1 = gh.sum(axis=0)
        W2 -= lr * dW2; b2 -= lr * db2; W1 -= lr * dW1; b1 -= lr * db1
    acc_float = (p.argmax(1) == y).mean()

    s1 = np.abs(W1).max() / 127.0
    s2 = np.abs(W2).max() / 127.0
    W1q = np.round(W1 / s1).astype(np.int32)
    W2q = np.round(W2 / s2).astype(np.int32)
    b1q = np.round(b1 / s1 * 127).astype(np.int32)
    b2q = np.round(b2 / s2 * 127).astype(np.int32)

    def infer_int(xint):
        acc1 = (W1q.T * xint).sum(axis=1) + b1q
        h = np.clip(acc1 >> SHIFT1, 0, 127)
        acc2 = (W2q.T * h).sum(axis=1) + b2q
        return int(acc2.argmax())

    Xint = np.clip((Xi * 127 / feat_max), 0, 127).astype(np.int64)
    preds = np.array([infer_int(x) for x in Xint])
    acc_int = (preds == y).mean()
    print(f"float acc={acc_float:.3f}  int8 acc={acc_int:.3f}  (n={len(X)}, classes=idle/walk/shake)")

    def arr2d(a):
        return "[" + ", ".join("[" + ", ".join(str(int(v)) for v in row) + "]" for row in a) + "]"

    def arr1d(a):
        return "[" + ", ".join(str(int(v)) for v in a) + "]"

    rs = f"""//! GENERATED by tools/train_motion3_nn.py - do not edit by hand.
//! A {FEAT}->{HIDDEN}->{NUM_CLASSES} int8 MLP motion classifier (idle/walk/shake),
//! trained on synthetic IMU |accel| windows. Integer-only inference.
pub const WINDOW: usize = {WINDOW};
pub const HIDDEN: usize = {HIDDEN};
pub const FEAT: usize = {FEAT};
pub const NUM_CLASSES: usize = {NUM_CLASSES};
pub const SHIFT1: u32 = {SHIFT1};
pub const FEAT_MAX: [i32; FEAT] = {arr1d(feat_max)};
pub const W1: [[i8; FEAT]; HIDDEN] = {arr2d(W1q.T)};
pub const B1: [i32; HIDDEN] = {arr1d(b1q)};
pub const W2: [[i8; HIDDEN]; NUM_CLASSES] = {arr2d(W2q.T)};
pub const B2: [i32; NUM_CLASSES] = {arr1d(b2q)};
pub const TRAIN_ACC_MILLI: u32 = {int(acc_int * 1000)};
"""
    with open(OUT, "w") as f:
        f.write(rs)
    print(f"wrote {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
