#!/usr/bin/env python3
"""M115: int8 keyword spotting ("yes" vs "no") - public data, host-trained, on-device.

Uses Google's Speech Commands v0.02 (public). Features are a small log-energy
spectrogram (15 frames x 8 bands = 120 values) computed with numpy's rfft - the same
math a device implementation would run. The dense classifier is int8-exported through
nobro_rtos.nn_export and generated into an ESP32 binary that classifies held-out
utterances on-device with nobro-nn: `NOBRO-KWS hits=.. host_parity=.. all_pass=..`.

  python3 tools/train_kws_pipeline.py --data <dir with yes/ and no/ folders>
"""
import argparse
import json
import random
import sys
import wave
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "bindings" / "python"))
from nobro_rtos.nn_export import dense, evaluate, export_model, train_dense  # noqa: E402

FRAMES, BANDS = 15, 8
N_IN = FRAMES * BANDS


def pcm_features(raw):
    x = np.zeros(16000, dtype=np.float32)
    x[: min(len(raw), 16000)] = raw[:16000] / 32768.0
    feats = []
    hop = 16000 // FRAMES
    for t in range(FRAMES):
        seg = x[t * hop : t * hop + 1024]
        if len(seg) < 1024:
            seg = np.pad(seg, (0, 1024 - len(seg)))
        spec = np.abs(np.fft.rfft(seg * np.hanning(1024))) ** 2
        # 8 log-spaced bands over 0..8 kHz
        edges = np.logspace(np.log10(4), np.log10(len(spec) - 1), BANDS + 1).astype(int)
        for b in range(BANDS):
            e = spec[edges[b] : max(edges[b + 1], edges[b] + 1)].mean()
            feats.append(float(np.log10(e + 1e-9)))
    f = np.array(feats)
    f = (f - f.mean()) / (f.std() + 1e-6)  # per-utterance normalization
    return [float(v) for v in f]


def wav_features(path: Path):
    with wave.open(str(path), "rb") as f:
        if f.getframerate() != 16000 or f.getnchannels() != 1:
            return None
        raw = np.frombuffer(f.readframes(f.getnframes()), dtype=np.int16)
    return pcm_features(raw)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", default="_work/datasets/speech")
    ap.add_argument("--out", default="core/ports/esp32s3/src/bin/kws_infer.rs")
    ap.add_argument("--per-class", type=int, default=700)
    ap.add_argument("--epochs", type=int, default=25)
    ap.add_argument("--test-samples", type=int, default=16)
    ap.add_argument("--json-out", default=None,
                    help="optional live-audio JSON model path, usually under _work")
    args = ap.parse_args()

    rng = random.Random(7)
    xs, ys = [], []
    for label, word in enumerate(["no", "yes"]):
        files = sorted((Path(args.data) / word).glob("*.wav"))
        rng.shuffle(files)
        n = 0
        for p in files:
            feat = wav_features(p)
            if feat is not None:
                xs.append(feat)
                ys.append(label)
                n += 1
            if n >= args.per_class:
                break
        print(f"{word}: {n} utterances")

    from sklearn.model_selection import train_test_split
    xtr, xte, ytr, yte = train_test_split(xs, ys, test_size=0.25, random_state=7)
    print(f"training {len(xtr)} samples ({N_IN} -> 2 dense, {args.epochs} epochs)...")
    w, b = train_dense(xtr, ytr, in_len=N_IN, out_len=2, epochs=args.epochs, lr=0.01)
    acc_tr, acc_te = evaluate(xtr, ytr, w, b), evaluate(xte, yte, w, b)
    print(f"host accuracy: train={acc_tr:.3f} test={acc_te:.3f}")

    model = export_model("kws-yes-no", 1, w, b, input_len=N_IN)
    print(f"int8 export: {len(model.weights)} bytes, scale_milli={model.scale_milli}")

    if args.json_out:
        json_path = Path(args.json_out)
        json_path.parent.mkdir(parents=True, exist_ok=True)
        json_path.write_text(json.dumps({
            "name": "kws-yes-no",
            "kind": "keyword-spotting-dense",
            "labels": ["no", "yes"],
            "feature_mode": "rfft-log-energy",
            "sample_rate_hz": 16000,
            "frames": FRAMES,
            "bands": BANDS,
            "input_len": N_IN,
            "output_len": 2,
            "weights": w,
            "bias": b,
            "threshold": 0.0,
            "train_accuracy": acc_tr,
            "test_accuracy": acc_te,
        }, indent=2), encoding="utf-8")
        print(f"wrote {json_path}")

    dev_x, dev_y = xte[: args.test_samples], yte[: args.test_samples]
    host_pred = [max(range(2), key=lambda j: dense(s, w, b)[j]) for s in dev_x]

    wq = ", ".join(str(int.from_bytes(bytes([q]), "big", signed=True)) for q in model.weights)
    samples = ",\n    ".join("[" + ", ".join(f"{v:.4f}" for v in s) + "]" for s in dev_x)
    labels = ", ".join(str(v) for v in dev_y)
    hpred = ", ".join(str(v) for v in host_pred)
    n_w = len(w)

    rust = f"""//! GENERATED by tools/train_kws_pipeline.py (M115) - do not edit by hand.
//!
//! "yes"/"no" keyword spotter (Google Speech Commands v0.02, 15x8 log-energy
//! spectrogram features), int8-quantized by nn_export, executed on-device by nobro-nn.
//! Host reference: train acc {acc_tr:.3f}, test acc {acc_te:.3f}.
#![no_std]
#![no_main]

use esp_hal::delay::Delay;
use esp_println::println;
use nobro_nn::{{argmax, dense}};

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {{
    loop {{}}
}}

const SCALE_MILLI: i32 = {model.scale_milli};
const WQ: [i8; {len(model.weights)}] = [{wq}];
const SAMPLES: [[f32; {N_IN}]; {args.test_samples}] = [
    {samples},
];
const LABELS: [u8; {args.test_samples}] = [{labels}];
const HOST_PRED: [u8; {args.test_samples}] = [{hpred}];

#[esp_hal::main]
fn main() -> ! {{
    let _p = esp_hal::init(esp_hal::Config::default());
    let delay = Delay::new();

    static mut W: [f32; {n_w}] = [0.0; {n_w}];
    let mut b = [0.0f32; 2];
    let w = unsafe {{ &mut *core::ptr::addr_of_mut!(W) }};
    for (i, &q) in WQ.iter().enumerate() {{
        let v = q as f32 * SCALE_MILLI as f32 / 1000.0;
        if i < {n_w} {{ w[i] = v; }} else {{ b[i - {n_w}] = v; }}
    }}

    let mut hits = 0u32;
    let mut parity = 0u32;
    for (i, sample) in SAMPLES.iter().enumerate() {{
        let mut out = [0.0f32; 2];
        dense(sample, w, &b, &mut out);
        let pred = argmax(&out) as u8;
        if pred == LABELS[i] {{ hits += 1; }}
        if pred == HOST_PRED[i] {{ parity += 1; }}
    }}
    let total = SAMPLES.len() as u32;
    let all_pass = u32::from(hits * 10 >= total * 8 && parity == total);

    loop {{
        println!(
            "NOBRO-KWS hits={{}} total={{}} host_parity={{}} all_pass={{}}",
            hits, total, parity, all_pass
        );
        delay.delay_millis(1000);
    }}
}}
"""
    Path(args.out).write_text(rust, encoding="utf-8")
    print(f"wrote {args.out}")
    print(f"RESULT: {'PASS' if acc_te >= 0.80 else 'FAIL'} (host test accuracy gate 0.80)")
    return 0 if acc_te >= 0.80 else 1


if __name__ == "__main__":
    sys.exit(main())
