#!/usr/bin/env python3
"""M101: full host-train -> int8 export -> on-device inference pipeline.

Trains a dense classifier on scikit-learn's built-in 8x8 digits dataset (public,
ships with sklearn, no download), quantizes it with nobro_rtos.nn_export (the same
int8 format nobro-ai validates), and generates a self-contained Rust binary for an
ESP32 port that runs nobro-nn inference over held-out test samples on the device.
The device reports its own accuracy: `NOBRO-DIGITS hits=N total=M all_pass=1`.

  python3 tools/train_digits_pipeline.py [--out core/ports/esp32s3/src/bin/digits_infer.rs]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "bindings" / "python"))
from nobro_rtos.nn_export import dense, evaluate, export_model, train_dense  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="core/ports/esp32s3/src/bin/digits_infer.rs")
    ap.add_argument("--epochs", type=int, default=40)
    ap.add_argument("--test-samples", type=int, default=24)
    args = ap.parse_args()

    from sklearn.datasets import load_digits
    from sklearn.model_selection import train_test_split

    digits = load_digits()
    x = [[v / 16.0 for v in row] for row in digits.data]  # 0..16 -> 0..1
    y = list(digits.target)
    xtr, xte, ytr, yte = train_test_split(x, y, test_size=0.25, random_state=7)

    print(f"training on {len(xtr)} samples (64 -> 10 dense, {args.epochs} epochs)...")
    w, b = train_dense(xtr, ytr, in_len=64, out_len=10, epochs=args.epochs, lr=0.02)
    acc_tr = evaluate(xtr, ytr, w, b)
    acc_te = evaluate(xte, yte, w, b)
    print(f"host accuracy: train={acc_tr:.3f} test={acc_te:.3f}")

    model = export_model("digits-8x8", 1, w, b, input_len=64)
    print(f"int8 export: {len(model.weights)} bytes, scale_milli={model.scale_milli}, "
          f"crc=0x{model.weights_crc:08X}")

    # Held-out device test set + the host's own predictions for parity checking.
    dev_x = xte[: args.test_samples]
    dev_y = yte[: args.test_samples]
    host_pred = [max(range(10), key=lambda j: dense(s, w, b)[j]) for s in dev_x]

    wq = ", ".join(str(int.from_bytes(bytes([raw]), "big", signed=True))
                   for raw in model.weights)
    samples = ",\n    ".join(
        "[" + ", ".join(f"{v:.4f}" for v in s) + "]" for s in dev_x
    )
    labels = ", ".join(str(v) for v in dev_y)
    hpred = ", ".join(str(v) for v in host_pred)

    rust = f"""//! GENERATED by tools/train_digits_pipeline.py (M101) - do not edit by hand.
//!
//! A dense 64->10 digit classifier trained on the public sklearn 8x8 digits set,
//! int8-quantized by nobro_rtos.nn_export, executed on-device by nobro-nn. The device
//! dequantizes the weights, classifies {args.test_samples} held-out samples, and
//! reports `NOBRO-DIGITS hits=.. host_parity=.. all_pass=..` over serial.
//! Host reference: train acc {acc_tr:.3f}, test acc {acc_te:.3f}.
#![no_std]
#![no_main]

use esp_hal::delay::Delay;
use esp_println::println;
use nobro_nn::{{argmax, dense}};

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {{
    loop {{}}
}}

const SCALE_MILLI: i32 = {model.scale_milli};
const WQ: [i8; {len(model.weights)}] = [{wq}];
const SAMPLES: [[f32; 64]; {args.test_samples}] = [
    {samples},
];
const LABELS: [u8; {args.test_samples}] = [{labels}];
const HOST_PRED: [u8; {args.test_samples}] = [{hpred}];

#[esp_hal::main]
fn main() -> ! {{
    let _p = esp_hal::init(esp_hal::Config::default());
    let delay = Delay::new();

    // dequantize: real = int8 * scale_milli / 1000 (nobro-ai WeightFormat::Int8)
    let mut w = [0.0f32; 640];
    let mut b = [0.0f32; 10];
    for (i, &q) in WQ.iter().enumerate() {{
        let v = q as f32 * SCALE_MILLI as f32 / 1000.0;
        if i < 640 {{ w[i] = v; }} else {{ b[i - 640] = v; }}
    }}

    let mut hits = 0u32;
    let mut parity = 0u32;
    for (i, sample) in SAMPLES.iter().enumerate() {{
        let mut out = [0.0f32; 10];
        dense(sample, &w, &b, &mut out);
        let pred = argmax(&out) as u8;
        if pred == LABELS[i] {{ hits += 1; }}
        if pred == HOST_PRED[i] {{ parity += 1; }}
    }}
    let total = SAMPLES.len() as u32;
    let all_pass = u32::from(hits * 10 >= total * 8 && parity == total);

    loop {{
        println!(
            "NOBRO-DIGITS hits={{}} total={{}} host_parity={{}} all_pass={{}}",
            hits, total, parity, all_pass
        );
        delay.delay_millis(1000);
    }}
}}
"""
    out = Path(args.out)
    out.write_text(rust, encoding="utf-8")
    print(f"wrote {out} ({len(rust)} bytes)")
    print(f"RESULT: {'PASS' if acc_te >= 0.85 else 'FAIL'} (host test accuracy gate 0.85)")
    return 0 if acc_te >= 0.85 else 1


if __name__ == "__main__":
    sys.exit(main())
