[package]
name = "nobro-adapter-mpu9250-imu"
version.workspace = true
edition.workspace = true
description = "Portable MPU9250/GY-9250/GY-91 SensorSal adapter"

[dependencies]
nobro-hal = { path = "../../../crates/nobro_hal", default-features = false, optional = true }
nobro-eh-i2c = { path = "../../bus/embedded-hal-i2c", default-features = false, optional = true }
nobro-kernel = { path = "../../../crates/nobro_kernel" }
nobro-imu = { path = "../../../crates/nobro_imu" }
nobro-sal = { path = "../../../crates/nobro_sal" }
embedded-hal = "1.0"
cortex-m = { version = "0.7", optional = true }
libm = "0.2"

[features]
default = ["board-promicro-nosd"]
nrf52840 = ["dep:cortex-m", "dep:nobro-hal", "dep:nobro-eh-i2c"]
board-promicro-nosd = [
    "nrf52840",
    "nobro-hal/board-promicro-nosd",
    "nobro-eh-i2c/board-promicro-nosd",
]
board-promicro-s140 = [
    "nrf52840",
    "nobro-hal/board-promicro-s140",
    "nobro-eh-i2c/board-promicro-s140",
]
board-nicenano-s140 = ["board-promicro-s140"]
