#!/usr/bin/env python3
"""Generate or verify the cross-language public API contract.

The manifest records exported names, normalized C declarations, exact source
digests, and signature-equivalent package mirrors (allowing only the generated
provenance banner). It contains no compiler output or machine-specific evidence.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "sdk" / "api-contract.json"
RUST_PUBLIC = re.compile(
    r"^\s*pub(?:\s*\([^)]*\))?\s+(fn|struct|enum|trait|type|const|static)\s+"
    r"([A-Za-z_][A-Za-z0-9_]*)",
    re.MULTILINE,
)
CPP_NAMED = re.compile(
    r"\b(?:class|struct|enum(?:\s+class)?|using)\s+([A-Za-z_][A-Za-z0-9_]*)"
)
C_TYPEDEF = re.compile(
    r"(?:}\s*|typedef\s+[^;{}\n]+\s+)([A-Za-z_][A-Za-z0-9_]*)\s*;"
)
C_MACRO = re.compile(r"^\s*#define\s+(NOBRO_[A-Za-z0-9_]+)\b", re.MULTILINE)
GENERATED_BANNER = re.compile(
    rb"^/\* GENERATED by [^\r\n]+\r?\n"
    rb" \* Do not edit here - edit the canonical header and re-run the sync\. \*/\r?\n"
)


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def canonical_text_bytes(path: Path) -> bytes:
    """Return repository-text bytes independent of checkout line endings."""

    return path.read_bytes().replace(b"\r\n", b"\n").replace(b"\r", b"\n")


def digest(path: Path) -> str:
    return hashlib.sha256(canonical_text_bytes(path)).hexdigest()


def cargo_name(lib: Path) -> str:
    cargo = lib.parents[1] / "Cargo.toml"
    match = re.search(
        r'^\s*name\s*=\s*"([^"]+)"',
        cargo.read_text(encoding="utf-8"),
        re.MULTILINE,
    )
    if match is None:
        raise ValueError(f"missing package name: {relative(cargo)}")
    return match.group(1)


def c_declarations(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", " ", text)
    text = re.sub(r"^\s*#.*$", " ", text, flags=re.MULTILINE)
    declarations = []
    for statement in text.split(";")[:-1]:
        normalized = " ".join(statement.split())
        if "(" in normalized and ")" in normalized:
            declarations.append(normalized + ";")
    return sorted(set(declarations))


def header_records(paths: list[Path], language: str) -> list[dict[str, object]]:
    records = []
    for path in paths:
        record: dict[str, object] = {
            "path": relative(path),
            "sha256": digest(path),
        }
        if language == "c":
            record["declarations"] = c_declarations(path)
            text = path.read_text(encoding="utf-8")
            record["named_types"] = sorted(set(C_TYPEDEF.findall(text)))
            record["macros"] = sorted(set(C_MACRO.findall(text)))
        else:
            record["named_types"] = sorted(
                set(CPP_NAMED.findall(path.read_text(encoding="utf-8")))
            )
        records.append(record)
    return records


def python_exports(path: Path) -> list[str]:
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    for node in tree.body:
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id == "__all__"
        ):
            value = ast.literal_eval(node.value)
            if not isinstance(value, list) or not all(
                isinstance(item, str) for item in value
            ):
                raise ValueError("Python __all__ must be a literal string list")
            if len(value) != len(set(value)):
                raise ValueError("Python __all__ contains duplicate exports")
            return value
    raise ValueError("Python package has no __all__")


def rust_records() -> list[dict[str, object]]:
    libs = sorted(
        (ROOT / "core" / "crates").glob("*/src/lib.rs")
    ) + sorted((ROOT / "core" / "adapters").glob("*/*/src/lib.rs"))
    libs += sorted((ROOT / "core" / "adapters").glob("*/*/*/src/lib.rs"))
    records = []
    for lib in libs:
        text = lib.read_text(encoding="utf-8")
        records.append(
            {
                "crate": cargo_name(lib),
                "path": relative(lib),
                "sha256": digest(lib),
                "exports": [
                    {"kind": kind, "name": name}
                    for kind, name in RUST_PUBLIC.findall(text)
                ],
            }
        )
    return records


def mirror_records() -> list[dict[str, object]]:
    groups: list[tuple[Path, list[Path]]] = []
    for source in sorted((ROOT / "bindings" / "c" / "include").glob("*.h")):
        targets = [
            ROOT / "sdk" / "include" / source.name,
            ROOT / "packages" / "arduino" / "src" / source.name,
            ROOT / "packages" / "platformio" / "include" / source.name,
        ]
        missing = [relative(target) for target in targets if not target.is_file()]
        if missing:
            raise ValueError(f"missing public mirrors for {relative(source)}: {missing}")
        groups.append((source, targets))
    for source in sorted((ROOT / "packages" / "arduino" / "src").glob("*.h")):
        if not source.name.startswith("Nobro"):
            continue
        target = ROOT / "packages" / "platformio" / "include" / source.name
        if not target.is_file():
            raise ValueError(f"missing PlatformIO mirror: {relative(target)}")
        groups.append((source, [target]))

    records = []
    for source, targets in groups:
        source_bytes = canonical_text_bytes(source)
        target_records = []
        for target in targets:
            target_bytes = canonical_text_bytes(target)
            normalized = GENERATED_BANNER.sub(b"", target_bytes, count=1)
            if normalized != source_bytes:
                raise ValueError(
                    f"public mirror drift: {relative(source)} != {relative(target)}"
                )
            target_records.append(
                {
                    "path": relative(target),
                    "sha256": hashlib.sha256(target_bytes).hexdigest(),
                    "generated_banner": target_bytes != source_bytes,
                }
            )
        records.append(
            {
                "source": relative(source),
                "source_sha256": hashlib.sha256(source_bytes).hexdigest(),
                "targets": target_records,
            }
        )
    return records


def build_manifest() -> dict[str, object]:
    c_headers = sorted((ROOT / "bindings" / "c" / "include").glob("*.h"))
    cpp_headers = sorted((ROOT / "bindings" / "cpp" / "include").glob("*.hpp"))
    python_init = ROOT / "bindings" / "python" / "nobro_rtos" / "__init__.py"
    python_modules = sorted(python_init.parent.glob("*.py"))
    return {
        "schema": "nobro-cross-language-api-v1",
        "generator": "tools/gen_api_contract.py",
        "surfaces": {
            "rust": rust_records(),
            "c": header_records(c_headers, "c"),
            "cpp": header_records(cpp_headers, "cpp"),
            "python": {
                "path": relative(python_init),
                "sha256": digest(python_init),
                "exports": python_exports(python_init),
                "modules": [
                    {"path": relative(path), "sha256": digest(path)}
                    for path in python_modules
                ],
            },
        },
        "signature_equivalent_mirrors": mirror_records(),
    }


def rendered_manifest() -> str:
    return json.dumps(build_manifest(), indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = rendered_manifest()
    if args.check:
        current = (
            DESTINATION.read_text(encoding="utf-8")
            if DESTINATION.is_file()
            else ""
        )
        if current != rendered:
            print("API CONTRACT: FAIL (run python tools/gen_api_contract.py)")
            return 1
        manifest = json.loads(rendered)
        surface_count = sum(
            len(value) if isinstance(value, list) else 1
            for value in manifest["surfaces"].values()
        )
        print(
            "API CONTRACT: PASS "
            f"({surface_count} surfaces, "
            f"{len(manifest['signature_equivalent_mirrors'])} mirror groups)"
        )
        return 0
    DESTINATION.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {relative(DESTINATION)}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"API CONTRACT: FAIL ({error})")
        sys.exit(1)
