#!/usr/bin/env python3
"""Generate an API index for NobroRTOS crates (M81).

Scans core/crates/*/src/lib.rs and categorized core/adapters/*/*/src/lib.rs for each crate's doc
comment and its public items (fn / struct / enum / trait), and writes docs/api-index.md.
Pure stdlib; keeps a browsable surface map in sync with the code.
"""
import argparse
import glob
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
PUB = re.compile(r"^pub(?:\s*\(crate\))?\s+(fn|struct|enum|trait)\s+([A-Za-z_][A-Za-z0-9_]*)")


def crate_name(lib):
    cargo = os.path.join(os.path.dirname(os.path.dirname(lib)), "Cargo.toml")
    if os.path.exists(cargo):
        for line in open(cargo, encoding="utf-8"):
            m = re.match(r'\s*name\s*=\s*"([^"]+)"', line)
            if m:
                return m.group(1)
    return os.path.basename(os.path.dirname(os.path.dirname(lib)))


def scan(lib):
    doc, items = [], {"trait": [], "struct": [], "enum": [], "fn": []}
    for line in open(lib, encoding="utf-8"):
        s = line.strip()
        if s.startswith("//!"):
            doc.append(s[3:].strip())
        m = PUB.match(s)
        if m:
            items[m.group(1)].append(m.group(2))
    summary = next((d for d in doc if d), "")
    return summary, items


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the tracked index is stale")
    args = parser.parse_args()
    libs = sorted(
        glob.glob(os.path.join(ROOT, "core", "crates", "*", "src", "lib.rs"))
        + glob.glob(os.path.join(ROOT, "core", "adapters", "*", "*", "src", "lib.rs"))
    )
    out = ["# NobroRTOS API Index", "",
           "_Generated by `tools/gen_api_index.py` from the crate sources._", ""]
    for lib in libs:
        name = crate_name(lib)
        summary, items = scan(lib)
        out.append(f"## `{name}`")
        if summary:
            out.append(f"{summary}")
        for kind in ("trait", "struct", "enum", "fn"):
            if items[kind]:
                names = ", ".join(f"`{n}`" for n in items[kind])
                out.append(f"- **{kind}**: {names}")
        out.append("")
    dest = os.path.join(ROOT, "docs", "api-index.md")
    rendered = "\n".join(out)
    pub_total = sum(
        len(scan(l)[1][k]) for l in libs for k in ("trait", "struct", "enum", "fn")
    )
    if args.check:
        current = open(dest, encoding="utf-8").read() if os.path.exists(dest) else ""
        if current != rendered:
            print("API INDEX: FAIL (run python tools/gen_api_index.py)")
            return 1
        print(f"API INDEX: PASS ({len(libs)} crates, {pub_total} public items)")
        return 0
    open(dest, "w", encoding="utf-8", newline="\n").write(rendered)
    print(f"wrote docs/api-index.md: {len(libs)} crates, {pub_total} public items")
    return 0


if __name__ == "__main__":
    sys.exit(main())
