#!/usr/bin/env python3
"""One-command project and diagnostic experience for NobroRTOS.

A single flow from "I have an idea" to a running, self-explaining app:

  nobro project new <name>            scaffold a workload + graph skeleton
  nobro project explain <workload>    explain the DERIVED contract in plain words
                                       (tasks, derived capabilities, startup order,
                                        marginal cost, schedulability, shed advice)
  nobro project run <project>         explain + real build + simulate + report
  nobro project report <report.json>  decode a project report

Everything generated lands under an ignored work root (`_work/projects/<name>`)
unless `--out` says otherwise, so a scaffold never dirties the tree.

    python tools/nobro_project.py new blinky
    python tools/nobro_project.py explain _work/projects/blinky/workload.json
    python tools/nobro_project.py --selftest

Exit 0 on success; explain exits 1 only when the workload is INFEASIBLE.
"""
import argparse
import json
import os
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import nobro_admission as adm  # noqa: E402  (marginal-cost + shed analysis)

DEFAULT_OUT = ROOT / "_work" / "projects"
NAME = re.compile(r"^[a-z][a-z0-9_-]{0,47}$")


# --------------------------------------------------------------- new (scaffold)

WORKLOAD_TEMPLATE = {
    "profile": {"flash": 128 * 1024, "ram": 32 * 1024, "pool": 8},
    "tasks": [
        {"name": "kernel", "criticality": "hard_realtime",
         "flash": 12 * 1024, "ram": 3 * 1024, "pool": 2,
         "period_us": 20_000, "budget_us": 0},
        {"name": "control", "criticality": "hard_realtime",
         "flash": 2 * 1024, "ram": 512, "period_us": 20_000, "budget_us": 2_000},
        {"name": "sensor", "criticality": "driver",
         "flash": 1 * 1024, "ram": 256, "period_us": 100_000, "budget_us": 2_000},
    ],
    "channels": [["sensor", "control"]],
}

GRAPH_SKELETON = '''\
// Generated by `nobro project new` — a graph-declared starting point.
// Build the contract once; the kernel derives manifest, startup, and tasks.
use nobro_kernel::{AppGraph, TaskDecl};

pub fn app() -> AppGraph<2> {
    AppGraph::<2>::new()
        .task(TaskDecl::control("control", 20_000)).unwrap()
        .task(TaskDecl::periodic("sensor", 100_000)).unwrap()
        .channel("sensor", "control").unwrap()
}
'''

RUST_CRITICALITY = {
    "best_effort": "BestEffort",
    "user": "User",
    "driver": "Driver",
    "system": "System",
    "hard_realtime": "HardRealtime",
}


def render_host_main(workload: dict) -> str:
    """Render the build input from the same workload that explain/simulate price."""
    startup_order(workload)
    tasks = [task for task in workload["tasks"] if task["name"] != "kernel"]
    chain = f"AppGraph::<{len(tasks)}>::new()\n"
    for task in tasks:
        name = json.dumps(task["name"])
        period = int(task.get("period_us", 0))
        if period <= 0:
            raise ValueError(f"task {task['name']}: build requires a positive period_us")
        criticality = task.get("criticality", "best_effort")
        constructor = {
            "hard_realtime": "control",
            "best_effort": "service",
        }.get(criticality, "periodic")
        expression = f"TaskDecl::{constructor}({name}, {period})"
        expression += f".criticality(Criticality::{RUST_CRITICALITY[criticality]})"
        if int(task.get("budget_us", 0)):
            expression += f".budget_us({int(task['budget_us'])})"
        if int(task.get("blocking_us", 0)):
            expression += f".blocking_us({int(task['blocking_us'])})"
        for dependency in task.get("after", []):
            expression += f".after({json.dumps(dependency)})"
        chain += f"        .task({expression}).unwrap()\n"
    for channel in workload.get("channels", []):
        chain += (f"        .channel({json.dumps(channel[0])}, "
                  f"{json.dumps(channel[1])}).unwrap()\n")
    chain += (f"        .build_for::<{len(tasks) + 1}>"
              "(SystemProfile::NRF52840_CORE).unwrap()")
    return (
        "// Generated from workload.json by `nobro project build`; edit the workload.\n"
        "use nobro_kernel::{AppGraph, Criticality, SystemProfile, TaskDecl};\n\n"
        "fn main() {\n"
        f"    let built = {chain};\n"
        "    println!(\"NOBRO_PROJECT tasks={} startup={} admitted=1\",\n"
        "             built.task_len, built.startup_len);\n"
        "}\n"
    )


def host_target() -> str:
    output = subprocess.check_output(["rustc", "-vV"], text=True)
    return next(line.split(":", 1)[1].strip()
                for line in output.splitlines() if line.startswith("host:"))


def checked_project(name: str, out_dir: pathlib.Path) -> pathlib.Path:
    if not NAME.fullmatch(name):
        raise ValueError("project name must match [a-z][a-z0-9_-]{0,47}")
    return out_dir.resolve() / name


def scaffold(name: str, out_dir: pathlib.Path) -> dict:
    project = checked_project(name, out_dir)
    (project / "src").mkdir(parents=True, exist_ok=True)
    (project / "workload.json").write_text(
        json.dumps(WORKLOAD_TEMPLATE, indent=2) + "\n", encoding="utf-8")
    (project / "app_graph.rs").write_text(GRAPH_SKELETON, encoding="utf-8")
    kernel_source = ROOT / "core" / "crates" / "nobro_kernel"
    try:
        kernel_path = os.path.relpath(kernel_source, project)
    except ValueError:
        # Windows cannot express a relative path across volumes. This path exists only
        # inside the user-selected generated project, never in a tracked artifact.
        kernel_path = str(kernel_source)
    cargo = (
        "[package]\n"
        f"name = \"nobro-project-{name.replace('_', '-')}\"\n"
        "version = \"0.1.0\"\n"
        "edition = \"2021\"\n"
        "publish = false\n\n"
        "[dependencies]\n"
        f"nobro-kernel = {{ path = {json.dumps(kernel_path)} }}\n"
        "critical-section = { version = \"1.2\", features = [\"std\"] }\n\n"
        "[workspace]\n"
    )
    (project / "Cargo.toml").write_text(cargo, encoding="utf-8", newline="\n")
    (project / "src" / "main.rs").write_text(
        render_host_main(WORKLOAD_TEMPLATE), encoding="utf-8")
    (project / "README.txt").write_text(
        f"NobroRTOS project '{name}'\n\n"
        f"Explain the derived contract:\n"
        f"  python tools/nobro_project.py explain {project / 'workload.json'}\n\n"
        f"The graph in app_graph.rs derives the whole kernel contract from one\n"
        f"declaration; workload.json prices it for admission.\n",
        encoding="utf-8")
    return {
        "name": name,
        "dir": str(project),
        "files": ["workload.json", "app_graph.rs", "Cargo.toml", "src/main.rs",
                  "README.txt"],
    }


def build_project(project: pathlib.Path) -> dict:
    manifest = project / "Cargo.toml"
    if not manifest.is_file():
        raise ValueError("project has no Cargo.toml; run `nobro project new` first")
    workload = json.loads((project / "workload.json").read_text(encoding="utf-8"))
    (project / "src" / "main.rs").write_text(
        render_host_main(workload), encoding="utf-8")
    command = ["cargo", "build", "--manifest-path", str(manifest),
               "--target", host_target()]
    completed = subprocess.run(command, cwd=ROOT, capture_output=True, text=True)
    return {
        "ok": completed.returncode == 0,
        "command": command,
        "detail": (completed.stdout + completed.stderr).splitlines()[-5:],
    }


def startup_order(workload: dict) -> list[str]:
    tasks = workload.get("tasks")
    if not isinstance(tasks, list) or not tasks:
        raise ValueError("tasks must be a non-empty list")
    names = [task.get("name") for task in tasks]
    if any(not isinstance(name, str) or not name for name in names):
        raise ValueError("every task needs a non-empty name")
    if len(set(names)) != len(names):
        duplicate = next(name for name in names if names.count(name) > 1)
        raise ValueError(f"duplicate task name: {duplicate}")
    if any(not NAME.fullmatch(name) for name in names):
        raise ValueError("task names must match [a-z][a-z0-9_-]{0,47}")
    if "kernel" not in names:
        raise ValueError("missing kernel task")
    for task in tasks:
        criticality = task.get("criticality", "best_effort")
        if criticality not in adm.CRITICALITY:
            raise ValueError(f"task {task['name']}: unknown criticality {criticality}")
        for field in ("flash", "ram", "pool", "period_us", "budget_us", "blocking_us"):
            if int(task.get(field, 0)) < 0:
                raise ValueError(f"task {task['name']}: {field} must be non-negative")
        if int(task.get("budget_us", 0)) > int(task.get("period_us", 0)):
            raise ValueError(f"task {task['name']}: budget_us exceeds period_us")
        if (int(task.get("budget_us", 0)) + int(task.get("blocking_us", 0))
                > int(task.get("period_us", 0))):
            raise ValueError(f"task {task['name']}: budget_us + blocking_us exceeds period_us")
        after = task.get("after", [])
        if not isinstance(after, list) or len(after) > 4 or len(set(after)) != len(after):
            raise ValueError(f"task {task['name']}: after must contain up to 4 unique names")
    known = set(names)
    dependencies = {name: set() for name in names}
    for task in tasks:
        for dependency in task.get("after", []):
            if dependency not in known:
                raise ValueError(f"task {task['name']}: unknown dependency {dependency}")
            dependencies[task["name"]].add(dependency)
    if dependencies["kernel"]:
        raise ValueError("kernel task cannot depend on an application task")
    for channel in workload.get("channels", []):
        if not isinstance(channel, list) or len(channel) != 2:
            raise ValueError("each channel must be [from, to]")
        for endpoint in channel:
            if endpoint not in known:
                raise ValueError(f"channel references unknown task {endpoint}")
    order = []
    remaining = set(names)
    while remaining:
        ready = [name for name in names if name in remaining
                 and not (dependencies[name] & remaining)]
        if not ready:
            cycle = next(name for name in names if name in remaining)
            raise ValueError(f"startup dependency cycle at task {cycle}")
        for name in ready:
            order.append(name)
            remaining.remove(name)
    # The kernel is always the first admitted node. Its dependency set is rejected
    # above, so moving it to the front preserves every valid application edge.
    return ["kernel"] + [name for name in order if name != "kernel"]


def simulate(project: pathlib.Path) -> tuple[pathlib.Path, dict]:
    workload_path = project / "workload.json"
    workload = json.loads(workload_path.read_text(encoding="utf-8"))
    startup_order(workload)
    analysis = adm.analyze(workload)
    feasible = analysis["schedulable"] or analysis["shed_plan"].get("feasible", False)
    report = {
        "schema": "nobro-project-report-v1",
        "mode": "simulation",
        "completed": True,
        "all_pass": feasible,
        "task_count": len(workload["tasks"]),
        "ticks": 100 if feasible else 0,
        "shed": analysis["shed_plan"].get("shed", []),
        "used": analysis["used"],
    }
    path = project / "reports" / "simulation.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path, report


def read_report(path: pathlib.Path) -> tuple[str, bool]:
    record = json.loads(path.read_text(encoding="utf-8"))
    if record.get("schema") == "nobro-project-report-v1":
        ok = bool(record.get("completed") and record.get("all_pass"))
        return (f"PROJECT REPORT: {'PASS' if ok else 'FAIL'} "
                f"mode={record.get('mode')} tasks={record.get('task_count')} "
                f"ticks={record.get('ticks')} shed={len(record.get('shed', []))}"), ok
    if "ok" in record and "app" in record:
        ok = bool(record.get("ok"))
        return (f"HARDWARE REPORT: {'PASS' if ok else 'FAIL'} "
                f"app={record.get('app')} completed={record.get('fields', {}).get('completed', 0)}"), ok
    raise ValueError("unknown report schema")


# ------------------------------------------------------------------- explain

def explain(workload: dict) -> tuple[str, bool]:
    """Plain-language account of the derived contract + admission verdict."""
    order = startup_order(workload)
    result = adm.analyze(workload)
    tasks = [t for t in workload["tasks"] if t["name"] != "kernel"]
    lines = [f"This system has {len(tasks)} task(s) plus the kernel."]

    # Derived capabilities: any task that shares a channel needs Mailbox; the
    # explain mirrors the graph's derivation rule.
    channels = workload.get("channels", [])
    if channels:
        endpoints = sorted({e for ch in channels for e in ch})
        lines.append(f"Channels are declared, so {', '.join(endpoints)} each get the "
                     f"Mailbox capability (the kernel owns it) — derived, not hand-written.")

    lines.append(f"Startup order: {' -> '.join(order)}.")

    # Marginal cost table + schedulability.
    lines.append("")
    lines.append(adm.render(result))
    lines.append("")
    if result["schedulable"]:
        flash_free = result["headroom"]["flash"]
        ram_free = result["headroom"]["ram"]
        util_free = result["headroom"]["util"] / 100
        lines.append(f"VERDICT: this admits. Headroom: {flash_free} B flash, "
                     f"{ram_free} B RAM, {util_free:.1f}% CPU. You can add more "
                     f"best-effort features until any of those reaches zero.")
        return "\n".join(lines), True

    plan = result["shed_plan"]
    if plan.get("feasible"):
        lines.append(f"VERDICT: over budget. The kernel would drop these best-effort "
                     f"tasks first (never your deadline-critical work): "
                     f"{', '.join(plan['shed'])}. Either accept that, cut a budget, "
                     f"or move to a bigger profile.")
        return "\n".join(lines), True
    lines.append("VERDICT: INFEASIBLE. Even after shedding every best-effort task the "
                 "deadline-critical core does not fit. Cut task budgets or choose a "
                 "bigger board profile — safety-critical work is never dropped.")
    return "\n".join(lines), False


# ------------------------------------------------------------------- selftest

def selftest() -> int:
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        out = pathlib.Path(tmp)
        # Golden session 1 — the SIMPLE path: scaffold -> explain -> admits.
        info = scaffold("blinky", out)
        assert {"workload.json", "app_graph.rs", "Cargo.toml", "src/main.rs"}.issubset(
            info["files"]
        )
        workload = json.loads((out / "blinky" / "workload.json").read_text(encoding="utf-8"))
        text, ok = explain(workload)
        assert ok and "VERDICT: this admits" in text, text
        built = build_project(out / "blinky")
        assert built["ok"], "\n".join(built["detail"])
        workload["tasks"].append(
            {"name": "telemetry", "criticality": "best_effort", "flash": 512,
             "ram": 128, "period_us": 250_000, "budget_us": 1_000,
             "after": ["sensor"]}
        )
        (out / "blinky" / "workload.json").write_text(
            json.dumps(workload, indent=2) + "\n", encoding="utf-8")
        rebuilt = build_project(out / "blinky")
        assert rebuilt["ok"], "\n".join(rebuilt["detail"])
        generated = (out / "blinky" / "src" / "main.rs").read_text(encoding="utf-8")
        assert 'TaskDecl::service("telemetry"' in generated and '.after("sensor")' in generated
        report_path, report = simulate(out / "blinky")
        assert report["all_pass"] and report_path.is_file()
        rendered, ok = read_report(report_path)
        assert ok and "PROJECT REPORT: PASS" in rendered

        # Golden session 2 — the COMPLEX path: the robotics workload over a tight
        # RAM profile explains, sheds best-effort first, and stays feasible.
        complex_wl = adm.robotics_workload()  # tight 8KB RAM -> over budget
        text, ok = explain(complex_wl)
        assert ok, "should be rescuable by shedding"
        assert "drop these best-effort tasks first" in text
        assert "camera_ai" in text and "motor" not in text.split("VERDICT")[1]

        # Golden session 3 — INFEASIBLE path exits non-ok.
        tiny = adm.robotics_workload()
        tiny["profile"] = {"flash": 4 * 1024, "ram": 1024, "pool": 1}
        _, ok = explain(tiny)
        assert not ok, "critical-core overflow must be infeasible"

        invalid = json.loads(json.dumps(WORKLOAD_TEMPLATE))
        invalid["tasks"][0]["after"] = ["sensor"]
        try:
            startup_order(invalid)
            raise AssertionError("a kernel dependency must be rejected")
        except ValueError as error:
            assert "kernel task cannot depend" in str(error)

    print("NOBRO PROJECT SELFTEST: PASS (scaffold/build/simulate/report)")
    return 0


# ------------------------------------------------------------------- main

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--selftest", action="store_true")
    sub = parser.add_subparsers(dest="command")

    p_new = sub.add_parser("new", help="scaffold a project")
    p_new.add_argument("name")
    p_new.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT)

    p_explain = sub.add_parser("explain", help="explain a workload's derived contract")
    p_explain.add_argument("workload", type=pathlib.Path)

    p_build = sub.add_parser("build", help="compile the generated graph scaffold")
    p_build.add_argument("project", type=pathlib.Path)

    p_sim = sub.add_parser("simulate", help="run bounded host admission simulation")
    p_sim.add_argument("project", type=pathlib.Path)

    p_report = sub.add_parser("report", help="read a project report")
    p_report.add_argument("report", type=pathlib.Path)

    p_run = sub.add_parser("run", help="explain, build, then simulate")
    p_run.add_argument("project", type=pathlib.Path)

    args = parser.parse_args()
    if args.selftest:
        return selftest()

    if args.command == "new":
        try:
            info = scaffold(args.name, args.out)
        except ValueError as error:
            print(f"cannot create project: {error}")
            return 1
        print(f"created project '{info['name']}' in {info['dir']}")
        print(f"  files: {', '.join(info['files'])}")
        print(f"  next:  python tools/nobro_project.py explain "
              f"{pathlib.Path(info['dir']) / 'workload.json'}")
        return 0

    if args.command == "explain":
        try:
            workload = json.loads(args.workload.read_text(encoding="utf-8"))
            text, ok = explain(workload)
        except (OSError, ValueError, KeyError, TypeError) as error:
            print(f"cannot explain workload: {error}")
            return 1
        print(text)
        return 0 if ok else 1

    if args.command == "build":
        try:
            result = build_project(args.project.resolve())
        except (OSError, ValueError, subprocess.SubprocessError) as error:
            print(f"PROJECT BUILD: FAIL ({error})")
            return 1
        print(f"PROJECT BUILD: {'PASS' if result['ok'] else 'FAIL'}")
        if not result["ok"]:
            print("\n".join(result["detail"]))
        return 0 if result["ok"] else 1

    if args.command == "simulate":
        try:
            path, record = simulate(args.project.resolve())
            rendered, ok = read_report(path)
        except (OSError, ValueError, KeyError, TypeError) as error:
            print(f"PROJECT SIMULATION: FAIL ({error})")
            return 1
        print(rendered)
        print(f"report: {path}")
        return 0 if ok and record["all_pass"] else 1

    if args.command == "report":
        try:
            rendered, ok = read_report(args.report)
        except (OSError, ValueError, TypeError) as error:
            print(f"REPORT: FAIL ({error})")
            return 1
        print(rendered)
        return 0 if ok else 1

    if args.command == "run":
        project = args.project.resolve()
        try:
            workload = json.loads((project / "workload.json").read_text(encoding="utf-8"))
            explanation, feasible = explain(workload)
            print(explanation)
            if not feasible:
                return 1
            built = build_project(project)
        except (OSError, ValueError, KeyError, TypeError, subprocess.SubprocessError) as error:
            print(f"PROJECT RUN: FAIL ({error})")
            return 1
        print(f"PROJECT BUILD: {'PASS' if built['ok'] else 'FAIL'}")
        if not built["ok"]:
            print("\n".join(built["detail"]))
            return 1
        path, _ = simulate(project)
        rendered, ok = read_report(path)
        print(rendered)
        print(f"PROJECT RUN: {'PASS' if ok else 'FAIL'}")
        return 0 if ok else 1

    parser.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
