#!/usr/bin/env python3
"""Declarative NobroRTOS app builder - describe hardware in JSON, no Rust required.

A beginner (or a non-Rust user, or a config generator) writes an app.json naming a board
and the actuators/sensors to mount from the built-in catalog. This tool validates every
choice against the catalog, prints a plain-language bring-up plan, and generates a Rust
`main.rs` skeleton that mounts exactly those modules (M191/M192/M194). The catalog here
mirrors the Rust `nobro-device` catalog, so JSON stays in lock-step with the firmware.

  python3 tools/nobro_app.py tutorials/hello-device/app.json           # validate + plan
  python3 tools/nobro_app.py tutorials/hello-device/app.json --gen out.rs
  python3 tools/nobro_app.py --selftest
"""
import argparse
import json
import os
import sys

BOARDS = {
    "nrf52840": {"feature": "board-promicro-nosd", "pwm_channels": 4},
    "rp2350": {"feature": "port-rp2350", "pwm_channels": 8},
    "esp32c3": {"feature": "port-esp32c3", "pwm_channels": 4},
}
SERVOS = {"generic_180", "sg90", "mg996r", "continuous"}
MOTORS = {"esc_unidir", "esc_bidir"}
SENSORS = {"mpu9250", "mpu6050", "icm45686", "ina3221", "bmp280"}
# AI/ML models: block editor ML blocks emit these; validated against the same rules the
# host AiModelContract enforces. Known ids come from the firmware adapters / train scripts.
AI_BACKENDS = {"on_device", "remote_api", "edge_sidecar", "hybrid"}
AI_MODELS = {0x4E4E4D31: "nn_motion", 0x4E4E4D33: "nn_motion3", 0x4D4F5431: "motion_variance"}
AI_POSITIVE_FIELDS = ("model_id", "input_bytes_max", "output_bytes_max",
                      "timeout_us", "stale_after_us")


def validate(app):
    errs = []
    board = app.get("board")
    if board not in BOARDS:
        errs.append(f"unknown board '{board}' (known: {sorted(BOARDS)})")
    n_pwm = BOARDS.get(board, {}).get("pwm_channels", 0)
    for a in app.get("actuators", []):
        brand = a.get("brand")
        if brand not in SERVOS and brand not in MOTORS:
            errs.append(f"actuator '{a.get('name')}': unknown brand '{brand}'")
        ch = a.get("channel", 0)
        if not (0 <= ch < n_pwm):
            errs.append(f"actuator '{a.get('name')}': channel {ch} out of range (0..{n_pwm-1})")
    for s in app.get("sensors", []):
        if s.get("brand") not in SENSORS:
            errs.append(f"sensor '{s.get('name')}': unknown brand '{s.get('brand')}'")
    for m in app.get("ai_models", []):
        mid = m.get("model_id")
        if m.get("backend") not in AI_BACKENDS:
            errs.append(f"ai_model {mid}: unknown backend '{m.get('backend')}'")
        for k in AI_POSITIVE_FIELDS:
            if not isinstance(m.get(k), int) or m.get(k, 0) <= 0:
                errs.append(f"ai_model {mid}: {k} must be a positive integer")
        if m.get("arena_bytes", 0) < 0:
            errs.append(f"ai_model {mid}: arena_bytes cannot be negative")
    return errs


def plan(app):
    print(f"=== NobroRTOS app: {app.get('name', 'unnamed')} ===")
    print(f"board: {app['board']}  (feature {BOARDS[app['board']]['feature']})")
    for a in app.get("actuators", []):
        print(f"  actuator {a['name']}: {a['brand']} on PWM channel {a.get('channel', 0)}")
    for s in app.get("sensors", []):
        print(f"  sensor   {s['name']}: {s['brand']} on {s.get('bus', 'i2c')}"
              + (f" @ {s['address']}" if 'address' in s else ""))
    for t in app.get("behaviors", []):
        print(f"  behavior: {t}")
    for m in app.get("ai_models", []):
        known = AI_MODELS.get(m.get("model_id"), "custom")
        print(f"  ai model {m.get('model_id')} ({known}): {m.get('backend')} "
              f"{m.get('input_bytes_max')}->{m.get('output_bytes_max')}B, "
              f"{m.get('timeout_us')}us budget")


CONST = {"generic_180": "SERVO_GENERIC_180", "sg90": "SERVO_SG90",
         "mg996r": "SERVO_MG996R", "continuous": "SERVO_CONTINUOUS",
         "esc_unidir": "ESC_UNIDIR", "esc_bidir": "ESC_BIDIR"}


def generate_rust(app):
    lines = [
        "// GENERATED by tools/nobro_app.py from app.json - a config-driven NobroRTOS app.",
        "#![no_std]",
        "#![no_main]",
        "use cortex_m_rt::entry;",
        "use panic_halt as _;",
        "use nobro_device::catalog::*;",
        "",
        "#[entry]",
        "fn main() -> ! {",
    ]
    for a in app.get("actuators", []):
        c = CONST.get(a["brand"], "SERVO_GENERIC_180")
        lines.append(f"    let {a['name']} = {c}; // PWM channel {a.get('channel', 0)}")
        lines.append(f"    let _center = {a['name']}.center_us;")
    for s in app.get("sensors", []):
        lines.append(f"    // sensor {s['name']} ({s['brand']}) - bind a driver from the catalog")
    lines += ["    loop { cortex_m::asm::wfi(); }", "}", ""]
    return "\n".join(lines)


def selftest():
    app = {
        "name": "hello_device",
        "board": "nrf52840",
        "actuators": [{"name": "arm", "brand": "sg90", "channel": 0}],
        "sensors": [{"name": "imu", "brand": "mpu6050", "bus": "i2c", "address": "0x68"}],
        "behaviors": ["sweep arm 0->180 when imu detects a tap"],
        "ai_models": [{"model_id": 0x4E4E4D31, "backend": "on_device",
                       "input_bytes_max": 64, "output_bytes_max": 4, "arena_bytes": 256,
                       "timeout_us": 2000, "stale_after_us": 100000}],
    }
    errs = validate(app)
    ok = not errs
    plan(app)
    print("\ngenerated Rust skeleton:")
    print(generate_rust(app))
    # negative case: bad brand + bad channel must be caught
    bad = {"board": "nrf52840",
           "actuators": [{"name": "x", "brand": "nope", "channel": 99}],
           "sensors": [{"name": "y", "brand": "unknownsensor"}]}
    bad_errs = validate(bad)
    ok = ok and len(bad_errs) == 3
    print(f"\nvalidation caught {len(bad_errs)} errors in the bad app (expect 3)")
    # negative case: a malformed ML model (bad backend + 4 missing positive fields)
    bad_ml = {"board": "nrf52840", "ai_models": [{"model_id": 5, "backend": "nope"}]}
    bad_ml_errs = validate(bad_ml)
    ok = ok and len(bad_ml_errs) == 5
    print(f"validation caught {len(bad_ml_errs)} errors in the bad ML model (expect 5)")
    print(f"RESULT: {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("app", nargs="?")
    ap.add_argument("--gen", help="write a generated Rust skeleton to this path")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest:
        return selftest()
    if not args.app:
        ap.print_help()
        return 0
    app = json.load(open(args.app))
    errs = validate(app)
    plan(app)
    if errs:
        print("\nERRORS:")
        for e in errs:
            print(f"  - {e}")
        print("RESULT: FAIL")
        return 1
    if args.gen:
        with open(args.gen, "w", newline="\n") as f:
            f.write(generate_rust(app))
        print(f"\nwrote {args.gen}")
    print("RESULT: PASS (app is valid)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
