#!/usr/bin/env python3
"""Arduino library packager for NobroRTOS (Tier A distribution).

The Arduino library must be self-contained: Library Manager and git users get only the
`packages/arduino/` tree, so the canonical C ABI headers (`bindings/c/include/*.h`) are
VENDORED into `packages/arduino/src/` with a generated banner. The standalone
SDK and PlatformIO distribution receive the same checked copies, and every
independently distributed package receives the repository license. This tool:

  --sync    copy canonical headers into the package (the generation step)
  --check   verify the vendored copies match the canonical ones (CI drift gate)
  --zip     emit an installable archive under _work/

    python tools/package_arduino.py --sync
    python tools/package_arduino.py --check     # exit 1 on drift
    python tools/package_arduino.py --zip
"""
import argparse
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CANON = ROOT / "bindings" / "c" / "include"
PKG = ROOT / "packages" / "arduino"
SRC = PKG / "src"
SDK_INC = ROOT / "sdk" / "include"
PIO_INC = ROOT / "packages" / "platformio" / "include"
LICENSE = ROOT / "LICENSE"
HOST_CONTRACT = ROOT / "host" / "nobro-host-contract.json"
PYTHON_HOST_CONTRACT = (
    ROOT / "bindings" / "python" / "nobro_rtos" / "nobro-host-contract.json"
)
LICENSE_DESTINATIONS = (
    PKG / "LICENSE",
    ROOT / "packages" / "platformio" / "LICENSE",
    ROOT / "bindings" / "python" / "LICENSE",
)

BANNER = (
    "/* GENERATED by tools/package_arduino.py --sync from bindings/c/include/{name}.\n"
    " * Do not edit here - edit the canonical header and re-run the sync. */\n"
)


def vendored_text(h: Path) -> str:
    return BANNER.format(name=h.name) + h.read_text(encoding="utf-8")


def sync() -> int:
    SDK_INC.mkdir(parents=True, exist_ok=True)
    PIO_INC.mkdir(parents=True, exist_ok=True)
    for h in sorted(CANON.glob("*.h")):
        (SRC / h.name).write_text(vendored_text(h), encoding="utf-8", newline="\n")
        (SDK_INC / h.name).write_text(vendored_text(h), encoding="utf-8", newline="\n")
        (PIO_INC / h.name).write_text(vendored_text(h), encoding="utf-8", newline="\n")
        print(f"synced Arduino + SDK + PlatformIO: {h.name}")
    license_text = LICENSE.read_text(encoding="utf-8")
    for destination in LICENSE_DESTINATIONS:
        destination.write_text(license_text, encoding="utf-8", newline="\n")
        print(f"synced {destination.relative_to(ROOT)}")
    PYTHON_HOST_CONTRACT.write_text(
        HOST_CONTRACT.read_text(encoding="utf-8"),
        encoding="utf-8",
        newline="\n",
    )
    print(f"synced {PYTHON_HOST_CONTRACT.relative_to(ROOT)}")
    return 0


def check() -> int:
    stale = []
    for h in sorted(CANON.glob("*.h")):
        for dst in (SRC / h.name, SDK_INC / h.name, PIO_INC / h.name):
            if not dst.exists() or dst.read_text(encoding="utf-8") != vendored_text(h):
                stale.append(str(dst.relative_to(ROOT)))
    license_text = LICENSE.read_text(encoding="utf-8")
    for destination in LICENSE_DESTINATIONS:
        if (
            not destination.exists()
            or destination.read_text(encoding="utf-8") != license_text
        ):
            stale.append(str(destination.relative_to(ROOT)))
    if (
        not PYTHON_HOST_CONTRACT.exists()
        or PYTHON_HOST_CONTRACT.read_text(encoding="utf-8")
        != HOST_CONTRACT.read_text(encoding="utf-8")
    ):
        stale.append(str(PYTHON_HOST_CONTRACT.relative_to(ROOT)))
    if stale:
        print(f"DRIFT: distribution copies out of date: {', '.join(stale)}")
        print("fix: python tools/package_arduino.py --sync")
        print("RESULT: FAIL")
        return 1
    print(
        "distribution headers/licenses match canonical "
        f"({len(list(CANON.glob('*.h')))} headers, "
        f"{len(LICENSE_DESTINATIONS)} licenses, 1 Python contract)"
    )
    print("RESULT: PASS")
    return 0


def make_zip() -> int:
    rc = check()
    if rc:
        return rc
    out = ROOT / "_work" / "NobroRTOS-arduino.zip"
    out.parent.mkdir(exist_ok=True)
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for f in sorted(PKG.rglob("*")):
            if f.is_file() and "build" not in f.parts:
                z.write(f, Path("NobroRTOS") / f.relative_to(PKG))
    print(f"wrote {out} ({out.stat().st_size} bytes)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sync", action="store_true")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--zip", action="store_true")
    args = ap.parse_args()
    if args.sync:
        return sync()
    if args.zip:
        return make_zip()
    return check()


if __name__ == "__main__":
    sys.exit(main())
