#!/usr/bin/env python3
"""ROS .msg -> Rust struct + NobroRTOS bridge contract (the "import ROS messages" path).

ROS ships message definitions as .msg IDL; NobroRTOS bridges are bounded and hash-typed
(no strings on device - a stable FNV-1a32 of "pkg/Msg" identifies the type). This tool
parses a .msg, computes the deterministic on-wire size, and emits:

  * a self-contained no_std Rust module: a #[repr(C)] struct with fixed little-endian
    encode/decode and MESSAGE_TYPE / MESSAGE_TYPE_HASH / MAX_MESSAGE_BYTES constants, plus
    a helper that builds the nobro_sal RosTopicContract, and
  * the RosTopic contract fragment (JSON) that matches nobro_rtos.RosTopic.to_dict().

For hard-real-time determinism every field is fixed-size: bounded forms `string<=N` and
`T[<=N]` are pinned to their maximum N (no length prefix), and unbounded `string` / `T[]`
are rejected - a bounded bridge must know its worst-case buffer up front.

  python tools/ros_msg_gen.py sensor_msgs/Imu.msg --type sensor_msgs/Imu --gen-rust imu.rs
  python tools/ros_msg_gen.py --selftest

Emits nothing sensitive; the artifact is the generated code + contract.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "..", "bindings", "python"))
from nobro_rtos.contracts import stable_hash32  # exact device/host hash  # noqa: E402

# ROS primitive -> (Rust type, byte size). char/byte are the legacy ROS1 aliases.
PRIMITIVES = {
    "bool": ("bool", 1), "byte": ("u8", 1), "char": ("u8", 1),
    "int8": ("i8", 1), "uint8": ("u8", 1),
    "int16": ("i16", 2), "uint16": ("u16", 2),
    "int32": ("i32", 4), "uint32": ("u32", 4),
    "int64": ("i64", 8), "uint64": ("u64", 8),
    "float32": ("f32", 4), "float64": ("f64", 8),
}


class MsgError(ValueError):
    pass


def parse_field(line):
    """Return (rust_type, elem_size, count, field_name) for one .msg field line, or None
    for blanks/comments/constants. count>1 means a fixed array."""
    line = line.split("#", 1)[0].strip()
    if not line:
        return None
    parts = line.split()
    if len(parts) < 2:
        raise MsgError(f"cannot parse field: {line!r}")
    type_tok, name = parts[0], parts[1]
    if "=" in line:                       # constant definition - not on the wire
        return None

    # string / string<=N
    if type_tok == "string" or type_tok.startswith("string<="):
        if type_tok == "string":
            raise MsgError(f"unbounded string not allowed (use string<=N): {line!r}")
        n = int(type_tok.split("<=", 1)[1])
        return ("u8", 1, n, name)

    base, count = type_tok, 1
    if type_tok.endswith("]"):
        base, dim = type_tok[:-1].split("[", 1)
        if dim == "":
            raise MsgError(f"unbounded array not allowed (use T[N] or T[<=N]): {line!r}")
        count = int(dim[2:]) if dim.startswith("<=") else int(dim)
    if base.startswith("string<="):       # string<=N[K] etc. - keep it simple
        raise MsgError(f"arrays of strings are not supported: {line!r}")
    if base not in PRIMITIVES:
        raise MsgError(f"unsupported (non-primitive) type '{base}' in: {line!r} "
                       "- flatten nested messages first")
    rust, size = PRIMITIVES[base]
    return (rust, size, count, name)


def parse_msg(text):
    fields = []
    for line in text.splitlines():
        parsed = parse_field(line)
        if parsed:
            fields.append(parsed)
    if not fields:
        raise MsgError("no serializable fields found")
    return fields


def wire_size(fields):
    return sum(size * count for _rust, size, count, _name in fields)


def rust_struct_name(message_type):
    return message_type.rsplit("/", 1)[-1]


def gen_rust(message_type, fields):
    name = rust_struct_name(message_type)
    total = wire_size(fields)
    type_hash = stable_hash32(message_type)

    decls, enc, dec, off = [], [], [], 0
    for rust, size, count, fname in fields:
        if count == 1:
            decls.append(f"    pub {fname}: {rust},")
            enc.append(_enc_scalar(rust, size, fname, off))
            dec.append(_dec_scalar(rust, size, fname, off))
        else:
            decls.append(f"    pub {fname}: [{rust}; {count}],")
            enc.append(_enc_array(rust, size, count, fname, off))
            dec.append(_dec_array(rust, size, count, fname, off))
        off += size * count

    dec_fields = ", ".join(f[3] for f in fields)
    return f'''//! GENERATED by tools/ros_msg_gen.py from {message_type} - do not edit by hand.
//! Fixed-size, little-endian wire form of the ROS message "{message_type}" for a bounded
//! NobroRTOS bridge. The on-device type identity is a stable FNV-1a32 hash, never a string.
#![allow(dead_code)]

pub const MESSAGE_TYPE: &str = "{message_type}";
pub const MESSAGE_TYPE_HASH: u32 = 0x{type_hash:08X};
pub const MAX_MESSAGE_BYTES: usize = {total};

#[derive(Clone, Copy, Debug, Default, PartialEq)]
#[repr(C)]
pub struct {name} {{
{os.linesep.join(decls)}
}}

impl {name} {{
    pub const fn message_type_hash() -> u32 {{ MESSAGE_TYPE_HASH }}

    /// Little-endian pack into `buf`; returns the number of bytes written.
    pub fn encode(&self, buf: &mut [u8]) -> Option<usize> {{
        if buf.len() < MAX_MESSAGE_BYTES {{ return None; }}
{os.linesep.join(enc)}
        Some(MAX_MESSAGE_BYTES)
    }}

    /// Inverse of `encode`.
    pub fn decode(buf: &[u8]) -> Option<Self> {{
        if buf.len() < MAX_MESSAGE_BYTES {{ return None; }}
{os.linesep.join(dec)}
        Some(Self {{ {dec_fields} }})
    }}
}}
'''


def _enc_scalar(rust, size, fname, off):
    if rust == "bool":
        return f"        buf[{off}] = self.{fname} as u8;"
    return (f"        buf[{off}..{off + size}]"
            f".copy_from_slice(&self.{fname}.to_le_bytes());")


def _dec_scalar(rust, size, fname, off):
    if rust == "bool":
        return f"        let {fname} = buf[{off}] != 0;"
    return (f"        let {fname} = {rust}::from_le_bytes("
            f"buf[{off}..{off + size}].try_into().ok()?);")


def _enc_array(rust, size, count, fname, off):
    if rust == "bool":
        body = f"buf[{off} + i] = v as u8;"
    else:
        body = (f"buf[{off} + i * {size}..{off} + i * {size} + {size}]"
                f".copy_from_slice(&v.to_le_bytes());")
    return (f"        for (i, v) in self.{fname}.iter().enumerate() {{ let v = *v; {body} }}")


def _dec_array(rust, size, count, fname, off):
    default = "false" if rust == "bool" else f"0 as {rust}"
    if rust == "bool":
        elem = f"buf[{off} + i] != 0"
    else:
        elem = (f"{rust}::from_le_bytes("
                f"buf[{off} + i * {size}..{off} + i * {size} + {size}].try_into().ok()?)")
    return (f"        let mut {fname} = [{default}; {count}];\n"
            f"        for i in 0..{count} {{ {fname}[i] = {elem}; }}")


def contract_fragment(message_type, fields, topic_name, depth):
    return {
        "name": topic_name,
        "name_hash": stable_hash32(topic_name),
        "message_type": message_type,
        "message_type_hash": stable_hash32(message_type),
        "depth": depth,
        "max_message_bytes": wire_size(fields),
    }


IMU_MSG = """\
# a trimmed sensor_msgs/Imu for the bounded bridge
float64[4] orientation
float64[9] orientation_covariance
float64[3] angular_velocity
float64[3] linear_acceleration
uint8 flags
"""


def selftest():
    fields = parse_msg(IMU_MSG)
    size = wire_size(fields)
    thash = stable_hash32("sensor_msgs/Imu")
    rust = gen_rust("sensor_msgs/Imu", fields)
    # pinned expectations: (4+9+3+3)*8 + 1 = 153 bytes; hash matches contracts.stable_hash32
    ok = (size == 153
          and thash == stable_hash32("sensor_msgs/Imu")
          and "pub const MAX_MESSAGE_BYTES: usize = 153;" in rust
          and f"0x{thash:08X}" in rust)
    print(f"fields parsed      : {len(fields)}")
    print(f"wire size          : {size} bytes (expect 153)")
    print(f"message_type_hash  : 0x{thash:08X}")
    print(f"RESULT: {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser(description="ROS .msg -> Rust + bridge contract.")
    ap.add_argument("msg", nargs="?", help="path to a .msg file")
    ap.add_argument("--type", help="ROS message type 'pkg/Name' (default: from filename)")
    ap.add_argument("--topic", default="/topic", help="topic name for the contract fragment")
    ap.add_argument("--depth", type=int, default=4, help="queue depth for the contract")
    ap.add_argument("--gen-rust", help="write the generated Rust module here")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args()
    if args.selftest or not args.msg:
        return selftest()

    text = open(args.msg, encoding="utf-8").read()
    message_type = args.type or os.path.splitext(os.path.basename(args.msg))[0]
    try:
        fields = parse_msg(text)
    except MsgError as exc:
        sys.exit(f"parse error: {exc}")

    frag = contract_fragment(message_type, fields, args.topic, args.depth)
    print(json.dumps(frag, indent=2))
    if args.gen_rust:
        with open(args.gen_rust, "w", newline="\n", encoding="utf-8") as f:
            f.write(gen_rust(message_type, fields))
        print(f"wrote {args.gen_rust} ({wire_size(fields)} bytes/message)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
