#!/usr/bin/env python3
"""M100/M107: face/person-presence model - public data, host-trained, run on-device.

Positives: LFW faces (public, via sklearn), average-pooled to 16x16 grayscale.
Negatives: the same pixel statistics with the face structure destroyed (block-shuffled
patches + noise), so the classifier must learn spatial structure, not brightness.
The model is int8-exported through nobro_rtos.nn_export and generated into an ESP32
binary that classifies held-out samples on-device with nobro-nn, reporting
`NOBRO-FACE hits=.. total=.. host_parity=.. all_pass=..` over serial.

  python3 tools/train_face_pipeline.py [--out core/ports/esp32s3/src/bin/face_infer.rs]
"""
import argparse
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "bindings" / "python"))
from nobro_rtos.nn_export import dense, evaluate, export_model, train_dense  # noqa: E402

SIDE = 16
N_IN = SIDE * SIDE


def pool_to_16x16(img):
    h, w = img.shape
    out = []
    for r in range(SIDE):
        for c in range(SIDE):
            r0, r1 = r * h // SIDE, (r + 1) * h // SIDE
            c0, c1 = c * w // SIDE, (c + 1) * w // SIDE
            block = img[r0:max(r1, r0 + 1), c0:max(c1, c0 + 1)]
            out.append(float(block.mean()) / 255.0)
    return out


def destroy_structure(vec, rng):
    """Negative: same pixels, face structure removed (4x4 block shuffle + noise)."""
    blocks = []
    for br in range(0, SIDE, 4):
        for bc in range(0, SIDE, 4):
            blocks.append([vec[(br + r) * SIDE + (bc + c)] for r in range(4) for c in range(4)])
    rng.shuffle(blocks)
    out = [0.0] * N_IN
    i = 0
    for br in range(0, SIDE, 4):
        for bc in range(0, SIDE, 4):
            b = blocks[i]; i += 1
            for r in range(4):
                for c in range(4):
                    out[(br + r) * SIDE + (bc + c)] = min(1.0, max(0.0, b[r * 4 + c] + rng.uniform(-0.08, 0.08)))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="core/ports/esp32s3/src/bin/face_infer.rs")
    ap.add_argument("--epochs", type=int, default=12)
    ap.add_argument("--max-faces", type=int, default=1200)
    ap.add_argument("--test-samples", type=int, default=16)
    args = ap.parse_args()

    from sklearn.datasets import fetch_lfw_people
    from sklearn.model_selection import train_test_split

    rng = random.Random(7)
    lfw = fetch_lfw_people(min_faces_per_person=20, resize=0.4)
    faces = lfw.images[: args.max_faces] * (255.0 / lfw.images.max())
    print(f"LFW: {len(faces)} face images {lfw.images.shape[1]}x{lfw.images.shape[2]}")

    xs, ys = [], []
    for img in faces:
        pos = pool_to_16x16(img)
        xs.append(pos); ys.append(1)          # person present
        xs.append(destroy_structure(pos, rng)); ys.append(0)  # structure destroyed

    xtr, xte, ytr, yte = train_test_split(xs, ys, test_size=0.25, random_state=7)
    print(f"training {len(xtr)} samples ({N_IN} -> 2 dense, {args.epochs} epochs)...")
    w, b = train_dense(xtr, ytr, in_len=N_IN, out_len=2, epochs=args.epochs, lr=0.01)
    acc_tr, acc_te = evaluate(xtr, ytr, w, b), evaluate(xte, yte, w, b)
    print(f"host accuracy: train={acc_tr:.3f} test={acc_te:.3f}")

    model = export_model("face-16x16", 1, w, b, input_len=N_IN)
    print(f"int8 export: {len(model.weights)} bytes, scale_milli={model.scale_milli}")

    dev_x, dev_y = xte[: args.test_samples], yte[: args.test_samples]
    host_pred = [max(range(2), key=lambda j: dense(s, w, b)[j]) for s in dev_x]

    wq = ", ".join(str(int.from_bytes(bytes([raw]), "big", signed=True)) for raw in model.weights)
    samples = ",\n    ".join("[" + ", ".join(f"{v:.4f}" for v in s) + "]" for s in dev_x)
    labels = ", ".join(str(v) for v in dev_y)
    hpred = ", ".join(str(v) for v in host_pred)
    n_w = len(w)

    rust = f"""//! GENERATED by tools/train_face_pipeline.py (M100/M107) - do not edit by hand.
//!
//! Face/person-presence classifier (LFW positives vs structure-destroyed negatives,
//! 16x16 grayscale), int8-quantized by nn_export, executed on-device by nobro-nn.
//! Host reference: train acc {acc_tr:.3f}, test acc {acc_te:.3f}.
#![no_std]
#![no_main]

use esp_hal::delay::Delay;
use esp_println::println;
use nobro_nn::{{argmax, dense}};

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {{
    loop {{}}
}}

const SCALE_MILLI: i32 = {model.scale_milli};
const WQ: [i8; {len(model.weights)}] = [{wq}];
const SAMPLES: [[f32; {N_IN}]; {args.test_samples}] = [
    {samples},
];
const LABELS: [u8; {args.test_samples}] = [{labels}];
const HOST_PRED: [u8; {args.test_samples}] = [{hpred}];

#[esp_hal::main]
fn main() -> ! {{
    let _p = esp_hal::init(esp_hal::Config::default());
    let delay = Delay::new();

    static mut W: [f32; {n_w}] = [0.0; {n_w}];
    let mut b = [0.0f32; 2];
    let w = unsafe {{ &mut *core::ptr::addr_of_mut!(W) }};
    for (i, &q) in WQ.iter().enumerate() {{
        let v = q as f32 * SCALE_MILLI as f32 / 1000.0;
        if i < {n_w} {{ w[i] = v; }} else {{ b[i - {n_w}] = v; }}
    }}

    let mut hits = 0u32;
    let mut parity = 0u32;
    for (i, sample) in SAMPLES.iter().enumerate() {{
        let mut out = [0.0f32; 2];
        dense(sample, w, &b, &mut out);
        let pred = argmax(&out) as u8;
        if pred == LABELS[i] {{ hits += 1; }}
        if pred == HOST_PRED[i] {{ parity += 1; }}
    }}
    let total = SAMPLES.len() as u32;
    let all_pass = u32::from(hits * 10 >= total * 8 && parity == total);

    loop {{
        println!(
            "NOBRO-FACE hits={{}} total={{}} host_parity={{}} all_pass={{}}",
            hits, total, parity, all_pass
        );
        delay.delay_millis(1000);
    }}
}}
"""
    Path(args.out).write_text(rust, encoding="utf-8")
    print(f"wrote {args.out}")
    print(f"RESULT: {'PASS' if acc_te >= 0.85 else 'FAIL'} (host test accuracy gate 0.85)")
    return 0 if acc_te >= 0.85 else 1


if __name__ == "__main__":
    sys.exit(main())
